### ISSUE TITLE
npcomplexMagProj in non-FFT domain

### ISSUE THREAD

**Issue by vsraptor** [NeuromorphicComputationResearchProgram/Learning-with-Holographic-Reduced-Representations#1]
In the paper you mention that by using some sort of Projection you increase capacity of mem traces..

What is the formula/process for non-FFT domain ?

I translate it like : 

      x = (x+1e-5)/x

in either case what is the idea ?

PS> in my tests it seems that float32 is unusable. I have to use float64

**Comment by EdwardRaff** [comment]
We did not derive a projection operation that works in the reals, as our projection explicitly is a function of the transformed domain after the FFT by normalizing complex magnitude. As far as I'm aware you will have to do an FFT to perform the projection step.

**Comment by vsraptor** [comment]
is this the code :  

          c_proj = c_ish[0,:] + 1j * c_ish[1,:]

what is the logic/idea behind it ?
how much better it is ? i.e. item capacity of superposition

thanks

**Comment by EdwardRaff** [comment]
Figure 5 in the paper shows that with the projection capacity scales linearly with dimension, but without is sub-linear and much lower.

I’m not sure I understand your question. Your code does not have an FFT present? The code snipet on the GitHub page shows how to do the projection step in numpy.

**Comment by vsraptor** [comment]
my question is what does the projection npcomplexMagProj  do ?

1. Convert to complex  domain via fft
2. normalizes both parts
3. converts back to real

is that it ?

In a sense renormalizing "rejig" the values and makes them better representation of N(0,1/n) ?

**Comment by EdwardRaff** [comment]
Please see this section of the paper for the explanation. It's so that the complex magnitude is exactly equal to 1, instead of approximately equal because the HRR math assumes that this property is true - but the N(0, 1/n) alone does not guarantee that it is true. The project step has the sole job of enforcing a complex unit magnitude, that is all. 

<img width="811" alt="Screen Shot 2022-06-02 at 2 17 41 PM" src="https://user-images.githubusercontent.com/2008786/171699064-9c193694-3992-42c8-9557-6c7f44f3bc2c.png">

**Comment by vsraptor** [comment]
I see, thanks... as close to 1..as possible, got it
I was normalizing anyway for better results i.e.  x/np.linalg.norm(x)

but on a first tests with the FFT-proj seems to boost the dot product even more.. thanks

PS> how do i read  "Id  . d^-1"

**Comment by EdwardRaff** [comment]
>PS> how do i read "Id . d^-1"

A diagonal covariance matrix of `d` dimensions, where the diagonal values are `1/d`.

**Comment by vsraptor** [comment]
I got this from time to time : 
       
      RuntimeWarning: invalid value encountered in true_divide
      c_ish=c_ish/np.linalg.norm(c_ish, axis=0)

I think the norm is [nan,nan,.....], how do I solve it ?

here is what i do for the discrete case : 

        TYPE = np.float64
	EPS = np.finfo(TYPE).eps

	def normalize(a): 
		norm=np.linalg.norm(a)
		if norm == 0: return a/hsdp.EPS
		return a/norm

**Comment by EdwardRaff** [comment]
While I'm very happy you are interested in our code, we don't have the bandwidth to help you debug your own custom code and the larger missing context. 

I will throw out that npinfo'a EPS value is going to be far too small for most use cases and not successfully defend against numerical issues in most cases. Especially if you divide by EPS - that is something you never want to do. 

If you run into an issue with our code / technique well be happy to try and help.

**Comment by vsraptor** [comment]
no worry, I understand.. currently this is what I come up with : 

     def proj(x):# Normalize a vector x in complex domain.
		c = np.fft.rfft(x)
		# Look at real and image as if they were real
		c_ish = np.vstack([c.real, c.imag])
		# Normalize magnitude of each complex/real pair
		n = np.linalg.norm(c_ish, axis=0)
		if np.any(n==0): n[n == 0] = hsdp.EPS
		c_ish=c_ish/n
		c_proj = c_ish[0,:] + 1j * c_ish[1,:]
		return np.fft.irfft(c_proj,n=x.shape[-1])

I will play with it and reread the paper to understand the process , so I can find a better solution

Ooo I  see EPS is too big e-16 and float64 is e-308
