### ISSUE TITLE
CC : torch vs numpy

### ISSUE THREAD

**Issue by vsraptor** [NeuromorphicComputationResearchProgram/Learning-with-Holographic-Reduced-Representations#2]
https://github.com/NeuromorphicComputationResearchProgram/Learning-with-Holographic-Reduced-Representations/blob/main/lib/mathops.py

the torch version of CC uses complex_multiplication() .. numpy version does not

Does this version returns different result  ?

**Comment by EdwardRaff** [comment]
The PyTorch version was originally written before it had support for complex numbers, so complex multiplication was done manually. Numpy has built-in support for complex numbers, so does not need the function. 

You may also be interested in @mahmudulalam256   who has created a small library for HRRs https://github.com/MahmudulAlam/Holographic-Reduced-Representations

**Comment by vsraptor** [comment]
thanks, thats what i'm building too..but much more ;)

Already did Kanerva-hypervectors and Numenta SDR

https://vsraptor.github.io/book/docs/ihtm/isdp.html
https://vsraptor.github.io/book/docs/bi/Bi_framework.html

but HRR seem the most promising... seems like I can build NLP and RL on top of it.. and Prolog like lang (like Bi, but this time with 'vector'-based unification!!)

thanks again..

**Comment by vsraptor** [comment]
here is part of my progress so far.. cant get the capacity past 5-10 (test at the end).... even when using yours fft_proj&fft_conv .. but not giving up ;)

But like u promised it is numerically stable ..check isclose() ...0.039 exact match.. if I switch to non-fft  it varies

-----

$ python3 base.py 

		norm: <function hsdp.fft_proj at 0x7ff9770b22f0>
		conv: <function hsdp.fft_convolution at 0x7ff9770b2488>
		inv: <cyfunction cy_involution at 0x7ff97710d6c8>
		corr: <cyfunction cy_correlation at 0x7ff97710d5f8>
		
 ok-pos : 1.000 : a % a
 ok : 1.000 : np.all(a == a)
 ok : 1.000 : a in (a + b)
==================== algebra ====================
-- comutativity
 ok-pos : 1.000 : (a + b) % (b + a)
-- comutativity
 ok-pos : 1.000 : (a * b) % (b * a)
-- associativity
 ok-pos : 1.000 : ((a + b) + c) % (a + (b + c))
-- associativity
 ok-pos : 1.000 : ((a * b) * c) % (a * (b * c))
-- distributivity
 ok-pos : 1.000 : ((a * b) + (a * c)) % (a * (b + c))
-- distributivity
 ok-pos : 1.000 : ((a * c) + (b * c)) % ((a + b) * c)
../hsdp.py:40: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b)) #cosine
 fail-pos : nan : (a * hsdp.zero(size)) % hsdp.zero(size)
-- additive identity
 ok-pos : 1.000 : (a + hsdp.zero(size)) % a
-- multiplicative identity
 ok-pos : 1.000 : (a * hsdp.one(size)) % a
==================== involution ====================
-- involution and sum
 ok-pos : 1.000 : +(a + b) % ((+a) + (+b))
-- involution and convolution
 ok-pos : 1.000 : +(a * b) % (+a * +b)
-- is equal
 ok : 1.000 : np.isclose( ((a * +b) % c) , (a % (b * c)), atol=0.01 )
 ok-neg : 0.039 : (a * +b) % c
 ok-neg : 0.039 : a % (b * c)
-- double involution is no involution
 ok-pos : 1.000 : a % ++a
==================== correlation ====================
123
((a * b) / a)
 fail-pos : 0.083 : ((a * b) // a) % b
123
(a / (a * b))
 ok-pos : 1.000 : (a // (a * b)) % b
==================== subtract ====================
 ok-pos : 1.000 : (a + b - a) % b
 ok-neg : 0.124 : (a + b - a) % a
==================== permute ====================
 ok-pos : 1.000 : ((a >> pvs.p1)<<pvs.p1) % a
-- roll test
 ok-pos : 1.000 : ((a >> 2)<<2) % a
-- close roll is orthogonal
 ok-neg : 0.000 : ((a >> 2)<<3) % a
==================== misc ====================
-- first * (name * Jane + age * 30)
 ok-pos : 0.720 : ( +(a * b) * (a * (b * c + d * e)) ) % c
----- sym tests -----
 ok : 1.000 : (a+b).sym == "(a + b)"
 ok : 1.000 : (a-b).sym == "(a - b)"
 ok : 1.000 : (a*b).sym == "(a * b)"
 fail : 0.000 : (a/b).sym == "(a / b)"
 ok : 1.000 : (a>>2).sym == "(a >> 2)"
 ok : 1.000 : (a<<2).sym == "(a << 2)"
 ok : 1.000 : (+a).sym == "#a"
 ok : 1.000 : (~a).sym == "~a"
----- capacity -----
pair count 1 : 1.000
pair count 2 : 0.715
pair count 3 : 0.629
pair count 4 : 0.551
pair count 5 : 0.432
pair count 6 : 0.471
pair count 7 : 0.325
